// Generated by gencpp from file slam/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SLAM_MESSAGE_ADDTWOINTS_H
#define SLAM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <slam/AddTwoIntsRequest.h>
#include <slam/AddTwoIntsResponse.h>


namespace slam
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::slam::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::slam::AddTwoInts > {
  static const char* value()
  {
    return "slam/AddTwoInts";
  }

  static const char* value(const ::slam::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::slam::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::slam::AddTwoInts > 
template<>
struct MD5Sum< ::slam::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam::AddTwoInts >::value();
  }
  static const char* value(const ::slam::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam::AddTwoIntsRequest> should match 
// service_traits::DataType< ::slam::AddTwoInts > 
template<>
struct DataType< ::slam::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::slam::AddTwoInts >::value();
  }
  static const char* value(const ::slam::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::slam::AddTwoInts > 
template<>
struct MD5Sum< ::slam::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam::AddTwoInts >::value();
  }
  static const char* value(const ::slam::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam::AddTwoIntsResponse> should match 
// service_traits::DataType< ::slam::AddTwoInts > 
template<>
struct DataType< ::slam::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::slam::AddTwoInts >::value();
  }
  static const char* value(const ::slam::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_MESSAGE_ADDTWOINTS_H
