# DO NOT EDIT THIS FILE
#
# To set up cross-compilation, create the file
# $(ROS_ROOT)/rostoolchain.cmake.  It gets read first, prior to 
# any of cmake's system tests.

#############################################################
#
# An example for using the gumstix arm-linux toolchain is below.
# Copy these lines to $(ROS_ROOT)/rostoolchain.cmake to try them out.
#
set(CMAKE_SYSTEM_NAME Linux)
set(DEVROOT $ENV{HOME}/robot)
set(PIROOT ${DEVROOT}/rootfs)
set(PITOOLS $ENV{HOME}/tools)

#set(TOOLROOT ${PITOOLS}/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian)
set(TOOLROOT ${PITOOLS}/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf)
#set(TOOLROOT $ENV{HOME}/tools_test/tools/arm-bcm2708/gcc-linaro-4.9-2015.02-3-x86_64_arm-linux-gnueabihf)

set(CMAKE_C_COMPILER ${TOOLROOT}/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER ${TOOLROOT}/bin/arm-linux-gnueabihf-g++)

set(CMAKE_SYSROOT ${PIROOT})
set(CMAKE_FIND_ROOT_PATH ${PIROOT})

# Have to set this one to BOTH, to allow CMake to find rospack
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

#############################################################
# Cross-compilation loader
#
# This file is passed to cmake on the command line via
# -DCMAKE_TOOLCHAIN_FILE.

#############################################################
# look for user's toolchain file in $ROS_ROOT/rostoolchain.cmake
find_file(TOOLCHAINCONFIG
          rostoolchain.cmake
          PATHS ENV ROS_ROOT
          NO_DEFAULT_PATH)
if(TOOLCHAINCONFIG)
  include(${TOOLCHAINCONFIG})
endif(TOOLCHAINCONFIG)
#############################################################
